apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: m5u4cq8k8-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-939557c51c.ps9p.p3.openshiftapps.com/rhtap/rhtap-qe:69991e3fec0390ffdebc141f6fcff5d421594271@sha256:fbbef045b586185a830b3af3039f721eb0cecfa5f43ebe00078796512fc03382
        name: container-image  
